services:

  auth-postgres:
    image: postgres:15
    container_name: omnistock_auth_postgres
    restart: always
    environment:
      POSTGRES_USER: auth_admin
      POSTGRES_PASSWORD: auth_password
      POSTGRES_DB: auth_service_db
    ports:
      - "5433:5432"
    volumes:
      - auth_postgres_data:/var/lib/postgresql/data

volumes:
  auth_postgres_data: